{{- if .Values.master.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "morphml.fullname" . }}-master-data
  labels:
    {{- include "morphml.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.master.persistence.storageClass }}
  {{- if (eq "-" .Values.master.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.master.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.master.persistence.size | quote }}
{{- end }}
